<?php
return array (
  1 => 
  array (
    'modelid' => '1',
    'siteid' => '1',
    'name' => '文章模型',
    'description' => '',
    'tablename' => 'news',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  12 => 
  array (
    'modelid' => '12',
    'siteid' => '1',
    'name' => '图片模型',
    'description' => '',
    'tablename' => 'picture',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  13 => 
  array (
    'modelid' => '13',
    'siteid' => '1',
    'name' => '成功案例模型',
    'description' => '',
    'tablename' => 'successcase',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list_successcase',
    'show_template' => 'show_successcase',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  14 => 
  array (
    'modelid' => '14',
    'siteid' => '1',
    'name' => '留言模型',
    'description' => '',
    'tablename' => 'messbook',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
  15 => 
  array (
    'modelid' => '15',
    'siteid' => '1',
    'name' => '招聘模型',
    'description' => '',
    'tablename' => 'jobinfo',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => '',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '0',
  ),
);
?>